name: CI

on:
  push:
    branches:
      - "*-dev"
    paths-ignore:
      - ".idea/**"
      - ".github/**.json"
      - ".gitignore"
      - ".gitmodules"
      - "**.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - ".idea/**"
      - ".github/**.json"
      - ".gitignore"
      - ".gitmodules"
      - "**.md"
      - "LICENSE"
  workflow_dispatch:
  workflow_call:

jobs:
  build-debug-apk:
    strategy:
      matrix:
        build-variant:
          [
            assembleLawnWithQuickstepNightlyRelease,
            assembleLawnWithQuickstepGithubDebug,
            assembleLawnWithQuickstepPlayDebug,
          ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: 21
      - uses: gradle/actions/setup-gradle@v6
        with:
          cache-encryption-key: Da25KUVSE5jbGds2zXmfXw==
      - name: Write sign info
        if: github.repository_owner == 'LawnchairLauncher'
        run: |
          if [ ! -z "${{ secrets.KEYSTORE }}" ]; then
            echo storePassword='${{ secrets.KEYSTORE_PASSWORD }}' >> keystore.properties
            echo keyAlias='${{ secrets.KEY_ALIAS }}' >> keystore.properties
            echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> keystore.properties
            echo storeFile='${{ github.workspace }}/key.jks' >> keystore.properties
            echo ${{ secrets.KEYSTORE }} | base64 --decode > ${{ github.workspace }}/key.jks
          fi
      - name: Build APK
        run: ./gradlew ${{ matrix.build-variant }}
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.build-variant }}
          path: build/outputs/apk/**/*.apk

  check-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: 21
      - uses: gradle/actions/setup-gradle@v6
      - run: ./gradlew spotlessCheck

  final-status:
    needs:
      - build-debug-apk
      - check-style
    runs-on: ubuntu-slim
    if: always()
    steps:
      - name: Check
        run: |
          results=$(tr -d '\n' <<< '${{ toJSON(needs.*.result) }}')
          if ! grep -q -v -E '(failure|cancelled)' <<< "$results"; then
            echo "One or more required jobs failed"
            exit 1
          fi
          echo "All required jobs completed successfully."
